logging:
  level:
    root: info
    com.socialgallery.gallerybackend: trace

server:
  port: 5000

spring:
  profiles:
    include:
      - oauth
      - jwt

  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}