logging:
  level:
    root: info
    com.socialgallery.gallerybackend: trace

server:
  port: 5000

spring:
  config:
    import: classpath:application-prod.yaml
    activate:
      on-profile: "prod"
  #  profiles:
#    include:
#      - oauth
#      - jwt
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            redirect-uri: ${baseurl}/oauth2/code/google
            scope: profile,email

  jwt:
    secret: ${jwt.secret}

  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.dbname}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}
  sql:
    init:
      schema-locations: classpath:mariadb:schema.sql

app:
  auth:
    token-secret: ${token-secret}
    token-expiration-msec: 300
  cors:
    allowedOrigins: http://localhost:3000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect